name: Test build with upstream Gtk+

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install devscripts equivs && sudo mk-build-deps --install
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-maemo-gtk=no --with-examples
    - name: make
      run: make -j $(nproc)
